id: P008247
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:10:33.013888
source_metadata:
  id: bdr:W1KG3982
  title: གཅོད་ཚོགས་
  author: ''
  volumes:
    55994c8fe8704be4885f9c5be4ae812b:
      image_group_id: I1KG4046
      title: ''
      volume_number: 1
      total_pages: 442
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
