id: P008247
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3982
  title: གཅོད་ཚོགས་
  author: ''
  volumes:
    55994c8fe8704be4885f9c5be4ae812b:
      image_group_id: I1KG4046
      title: ''
      volume_number: 1
      total_pages: 442
